import React, { useEffect, useState } from "react";
import { ExternalLink, Search, ShieldCheck } from "lucide-react";
import { api, TalentDiscoveryResponse } from "@/lib/api";
import { toast } from "sonner";

const initialFilters = { department: "", role: "", designation: "", competency: "", competency_domain: "", minimum_proficiency: "", minimum_confidence: "", training_status: "" };

export function TalentDiscovery({ onNavigate }: { onNavigate?: (page: string) => void }) {
  const [filters, setFilters] = useState(initialFilters);
  const [data, setData] = useState<TalentDiscoveryResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async (active = filters) => {
    try {
      setLoading(true);
      const params = Object.fromEntries(Object.entries(active).filter(([, value]) => value));
      setData(await api.admin.talentDiscovery(params));
    } catch (error: any) { toast.error(error?.message || "Failed to load talent discovery"); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const update = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }));

  return <div className="space-y-6 anim-page-enter">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#7c3aed]">Evidence-backed workforce planning</div><h1 className="mt-1 text-2xl font-extrabold tracking-tight text-[#123057]">Talent Discovery</h1><p className="mt-1 text-sm text-slate-500">Discover evidence-backed capabilities across the government workforce.</p></div><button onClick={() => load()} className="rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs font-bold text-slate-600">Refresh</button></div>
    <div className="grid gap-3 rounded-2xl border border-[#dfe7f0] bg-white p-4 sm:grid-cols-2 lg:grid-cols-4">{([ ["department", "Ministry / Department"], ["role", "Role"], ["designation", "Designation"], ["competency", "Competency"], ["competency_domain", "Competency domain"] ] as const).map(([key, label]) => <label key={key} className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}<input value={filters[key]} onChange={(event) => update(key, event.target.value)} className="form-input !mt-1" placeholder={label} /></label>)}<label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Minimum proficiency<input type="number" min="0" max="5" step="0.1" value={filters.minimum_proficiency} onChange={(event) => update("minimum_proficiency", event.target.value)} className="form-input !mt-1" placeholder="0-5" /></label><label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Evidence confidence<input type="number" min="0" max="1" step="0.05" value={filters.minimum_confidence} onChange={(event) => update("minimum_confidence", event.target.value)} className="form-input !mt-1" placeholder="0-1" /></label><label className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Training status<select value={filters.training_status} onChange={(event) => update("training_status", event.target.value)} className="form-input !mt-1"><option value="">All statuses</option><option value="assigned">Assigned</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></label><button onClick={() => load()} className="inline-flex items-center justify-center gap-2 self-end rounded-xl bg-[#123057] px-4 py-3 text-xs font-bold text-white"><Search size={14} /> Discover capabilities</button></div>
    <div className="flex items-center gap-2 rounded-xl border border-teal-100 bg-teal-50/60 px-4 py-3 text-xs text-teal-800"><ShieldCheck size={15} /> Results include active officials who explicitly opted into authorized opportunity discovery. This is decision support, not an employment recommendation.</div>
    {loading && !data ? <div className="rounded-2xl border border-[#dfe7f0] bg-white p-8 text-sm text-slate-500">Loading evidence-backed capabilities...</div> : data && <><div className="text-xs font-semibold text-slate-500">{data.total} relevant capability profile{data.total === 1 ? "" : "s"} found</div><div className="space-y-4">{data.results.map((result) => <article key={result.official.id} className="rounded-2xl border border-[#dfe7f0] bg-white p-5 shadow-xs"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="text-sm font-bold text-[#123057]">{result.official.name}</h2><p className="mt-1 text-xs text-slate-500">{result.current_role} · {result.designation} · {result.department}</p></div><div className="text-left sm:text-right"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Capability match</div><div className="text-2xl font-extrabold text-[#087f76]">{Math.round(result.capability_match * 100)}%</div></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{result.competencies.map((item) => <div key={item.code} className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="flex justify-between gap-2 text-xs"><span className="font-bold text-slate-700">{item.name}</span><span className="font-bold text-[#123057]">{item.current_proficiency.toFixed(1)} / 5</span></div><div className="mt-1 text-[10px] text-slate-500">{item.domain} · Confidence {Math.round(item.evidence_confidence * 100)}% · {item.supporting_evidence_count} evidence record{item.supporting_evidence_count === 1 ? "" : "s"}</div></div>)}</div><div className="mt-4 flex flex-col justify-between gap-3 border-t border-slate-100 pt-3 sm:flex-row sm:items-center"><div className="space-y-1 text-[11px] text-slate-500">{result.explanation.map((line) => <div key={line}>✓ {line}</div>)}<div>Recent learning activity: {result.recent_learning_activity}</div></div><button onClick={() => onNavigate?.("Users")} className="inline-flex items-center justify-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-bold text-[#123057] hover:bg-slate-50">View evidence <ExternalLink size={13} /></button></div></article>)}{!data.results.length && <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">No opt-in capability profiles match these filters.</div>}</div></>}
  </div>;
}

export default TalentDiscovery;
