"""Quiz service - business logic for quiz creation, submission, scoring, and competency updates."""
from datetime import UTC, datetime
from typing import Optional

from bson import ObjectId
from pymongo.database import Database

from app.competencies.models import EvidenceType
from app.assessments.repository import (
    insert_evidence,
    upsert_profile,
)
from app.quizzes import repository as quiz_repo
from app.quizzes.models import Quiz, QuizAttempt, QuizStatus, QuizQuestion


class QuizServiceError(Exception):
    """Quiz service error."""
    pass


class QuizService:
    """Quiz service with business logic."""

    def __init__(self, database: Database):
        self.db = database

    def create_quiz(
        self,
        user_id: str,
        material_id: str,
        competency_code: str,
        questions: list[dict],
    ) -> dict:
        """
        Create a quiz from pre-generated MCQs.
        
        Note: MCQs are generated by Phase 6 (/api/v1/materials/{material_id}/generate-questions).
        This endpoint receives the generated questions and stores them in a quiz.
        
        Flow:
        1. Validate user owns the material
        2. Validate material is READY
        3. Validate competency exists
        4. Store questions in quiz
        5. Return quiz
        """
        if not ObjectId.is_valid(user_id):
            raise QuizServiceError("Invalid user ID")
        if not ObjectId.is_valid(material_id):
            raise QuizServiceError("Invalid material ID")

        user_oid = ObjectId(user_id)
        material_oid = ObjectId(material_id)

        # Validate material exists and belongs to user
        material = self.db.learning_materials.find_one(
            {"_id": material_oid, "user_id": {"$in": [str(user_id), user_oid]}}
        )
        if not material:
            raise QuizServiceError("Material not found or does not belong to user")

        # Validate material is READY
        if material.get("status") != "READY":
            raise QuizServiceError(
                f"Material is not ready (status: {material.get('status')})"
            )

        # Validate competency exists
        competency = self.db.competencies.find_one({"code": competency_code})
        if not competency:
            raise QuizServiceError(f"Competency not found: {competency_code}")

        if not questions:
            raise QuizServiceError("No questions provided")

        # Convert generated MCQs to quiz questions (preserve all data)
        quiz_questions = []
        for idx, mcq in enumerate(questions):
            question = QuizQuestion(
                question_id=f"q_{idx + 1}",
                question=mcq["question"],
                options=mcq["options"],
                correct_answer=mcq["correct_answer"],
                explanation=mcq["explanation"],
                difficulty=mcq["difficulty"],
                source_chunks=mcq.get("source_chunks", []),
            )
            quiz_questions.append(dict(question))

        # Create quiz document
        quiz_doc = Quiz.create(
            user_id=user_oid,
            material_id=material_oid,
            competency_code=competency_code,
            title=f"{competency_code} Quiz - {material.get('original_filename')}",
            questions=quiz_questions,
            question_count=len(quiz_questions),
        )

        # Insert into database
        quiz_id = quiz_repo.insert_quiz(self.db, quiz_doc)
        quiz_doc["_id"] = quiz_id

        return quiz_doc

    def get_quiz(self, user_id: str, quiz_id: str) -> dict:
        """
        Retrieve a quiz (without correct answers).
        
        Correct answers must not be exposed before submission.
        """
        quiz = quiz_repo.get_quiz_by_id(self.db, quiz_id, user_id)
        if not quiz:
            raise QuizServiceError("Quiz not found")

        # Remove correct answers from questions before returning
        questions_for_response = []
        for q in quiz.get("questions", []):
            safe_question = {
                "question_id": q["question_id"],
                "question": q["question"],
                "options": q["options"],
                "difficulty": q["difficulty"],
                "source_chunks": q.get("source_chunks", []),
            }
            questions_for_response.append(safe_question)

        # Do not mutate the repository object while removing answer keys. The
        # same quiz must retain its persisted answer key for server-side scoring.
        response_quiz = dict(quiz)
        response_quiz["questions"] = questions_for_response
        return response_quiz

    def submit_quiz(
        self,
        user_id: str,
        quiz_id: str,
        answers: list[dict],
    ) -> dict:
        """
        Submit quiz answers and calculate score.
        
        Flow:
        1. Validate user owns quiz
        2. Validate quiz is not already submitted
        3. Validate all questions answered
        4. Calculate score server-side
        5. Create quiz attempt
        6. Create competency evidence
        7. Update competency profile (deterministic rule)
        8. Return result with before/after competency
        """
        # Get quiz
        quiz = quiz_repo.get_quiz_by_id(self.db, quiz_id, user_id)
        if not quiz:
            raise QuizServiceError("Quiz not found")

        # Check if already submitted
        if quiz.get("status") == QuizStatus.SUBMITTED:
            raise QuizServiceError("Quiz already submitted")

        existing_attempt = quiz_repo.get_quiz_attempt_by_quiz_id(self.db, quiz_id, user_id)
        if existing_attempt:
            raise QuizServiceError("Quiz already submitted")

        # Validate answers
        question_ids = {q["question_id"] for q in quiz["questions"]}
        submitted_ids = {a["question_id"] for a in answers}

        if submitted_ids != question_ids:
            raise QuizServiceError(
                f"Missing or extra question IDs. Expected {question_ids}, got {submitted_ids}"
            )

        # Check for duplicates
        if len(submitted_ids) != len([a["question_id"] for a in answers]):
            raise QuizServiceError("Duplicate question IDs in submission")

        # Create answer map
        answer_map = {a["question_id"]: a["selected_answer"] for a in answers}

        # Calculate score server-side
        correct_count = 0
        attempt_answers = []

        for question in quiz["questions"]:
            q_id = question["question_id"]
            selected = answer_map[q_id]
            correct = question["correct_answer"]
            is_correct = selected.upper() == correct.upper()

            if is_correct:
                correct_count += 1

            attempt_answers.append({
                "question_id": q_id,
                "selected_answer": selected.upper(),
                "is_correct": is_correct,
            })

        total_questions = len(quiz["questions"])
        percentage = (correct_count / total_questions * 100) if total_questions > 0 else 0

        # Create quiz attempt
        user_oid = ObjectId(user_id)
        attempt_doc = QuizAttempt.create(
            quiz_id=ObjectId(quiz_id),
            user_id=user_oid,
            answers=attempt_answers,
            score=correct_count,
            percentage=percentage,
            correct_count=correct_count,
            total_questions=total_questions,
        )

        attempt_id = quiz_repo.insert_quiz_attempt(self.db, attempt_doc)

        # Update quiz with score
        now = datetime.now(UTC)
        quiz_repo.update_quiz_with_score(
            self.db,
            quiz_id,
            user_id,
            correct_count,
            percentage,
            now,
        )

        # Get competency before update
        competency_code = quiz["competency_code"]
        competency_before = self._get_current_competency(user_oid, competency_code)

        # Get competency ObjectId
        competency_doc = self.db.competencies.find_one({"code": competency_code})
        competency_oid = ObjectId(competency_doc["_id"]) if competency_doc else ObjectId()

        # Create supporting evidence record (confidence = 0.30, authority = SUPPORTING)
        evidence_doc = {
            "_id": ObjectId(),
            "user_id": user_oid,
            "competency_code": competency_code,
            "competency_id": competency_oid,
            "evidence_type": EvidenceType.QUIZ,
            "type": "PRACTICE_QUIZ",
            "authority": "SUPPORTING",
            "source": "AI_QUIZ",
            "quiz_id": ObjectId(quiz_id),
            "attempt_id": ObjectId(attempt_id),
            "score_type": "PERCENTAGE",
            "raw_score": percentage,
            "quiz_percentage": percentage,
            "score": percentage,  # Native percentage
            "normalized_level": round(min(5.0, max(1.0, (percentage / 100.0) * 5.0)), 1),
            "confidence": 0.30,
            "weight": 0.30,  # Supporting evidence weight
            "notes": "Self-service quiz practice recorded as supporting evidence.",
            "created_at": now,
            "metadata": {
                "material_id": str(quiz.get("material_id") or ""),
                "question_count": total_questions,
                "correct_count": correct_count,
                "source_chunks": self._extract_all_source_chunks(quiz["questions"]),
            }
        }
        insert_evidence(self.db, evidence_doc)

        # Core Invariant: Supporting evidence (quizzes) MUST NOT modify the authoritative competency profile.
        # Competency profile remains unchanged until an authoritative assessment is completed.
        competency_after = {
            "level": competency_before["level"],
            "confidence": competency_before["confidence"],
        }

        # Skill gap remains unchanged (Supporting evidence does NOT mutate gap)
        skill_gap_before = self._calculate_skill_gap(user_oid, competency_code, competency_before)

        # Build explanations
        explanations = []
        for question in quiz["questions"]:
            q_id = question["question_id"]
            answer = next((a for a in attempt_answers if a["question_id"] == q_id), None)

            explanations.append({
                "question_id": q_id,
                "question": question["question"],
                "options": question["options"],
                "your_answer": answer["selected_answer"],
                "correct_answer": question["correct_answer"],
                "explanation": question["explanation"],
                "difficulty": question["difficulty"],
                "source_chunks": question.get("source_chunks", []),
                "is_correct": answer["is_correct"],
            })

        return {
            "_id": attempt_id,
            "quiz_id": quiz_id,
            "score": correct_count,
            "percentage": percentage,
            "correct_count": correct_count,
            "total_questions": total_questions,
            "competency": {
                "competency_code": competency_code,
                "competency_level_before": competency_before["level"],
                "competency_level_after": competency_after["level"],
                "confidence_before": competency_before["confidence"],
                "confidence_after": competency_after["confidence"],
                "improvement": 0.0,
            },
            "skill_gap": {
                "competency_code": competency_code,
                "current_level": competency_after["level"],
                "required_level": skill_gap_before["required_level"],
                "gap_before": skill_gap_before["gap"],
                "gap_after": skill_gap_before["gap"],
            },
            "explanations": explanations,
            "submitted_at": now,
        }

    def _get_current_competency(self, user_id: ObjectId, competency_code: str) -> dict:
        """Get current competency level and confidence for a user."""
        competency = self.db.competencies.find_one({"code": competency_code})
        if not competency:
            return {"level": 2.5, "confidence": 0.5}

        competency_oid = ObjectId(competency["_id"]) if isinstance(competency["_id"], str) else competency["_id"]
        
        profile = self.db.competency_profiles.find_one({
            "user_id": user_id,
            "competency_id": competency_oid,
        })

        if not profile:
            return {"level": 2.5, "confidence": 0.5}

        level = profile.get("current_level")
        if level is None:
            level = profile.get("level", 2.5)

        return {
            "level": float(level),
            "confidence": float(profile.get("confidence", 0.5)),
        }

    def _update_competency_deterministic(
        self,
        user_id: ObjectId,
        competency_code: str,
        quiz_percentage: float,
    ) -> dict:
        """
        Deprecated: In ShikshaSetu evidence governance, quizzes are Supporting Evidence
        and do NOT directly mutate competency_profiles.
        Returns the current competency state without modifying the profile.
        """
        return self._get_current_competency(user_id, competency_code)

    def _calculate_skill_gap(
        self,
        user_id: ObjectId,
        competency_code: str,
        competency_state: dict,
    ) -> dict:
        """
        Calculate skill gap for a competency.
        
        Reuses Phase 5 logic:
        gap = max(0, required_level - current_level)
        """
        user = self.db.users.find_one({"_id": user_id})
        role_id = user.get("role_id") if user else None
        
        competency = self.db.competencies.find_one({"code": competency_code})
        competency_oid = competency["_id"] if competency else None
        
        req = None
        if role_id and competency_oid:
            role_oid = ObjectId(role_id) if isinstance(role_id, str) and ObjectId.is_valid(role_id) else role_id
            req = self.db.role_requirements.find_one({"role_id": role_oid, "competency_id": competency_oid})
            
        required_level = float(req.get("required_level", 3.0)) if req else 3.0
        current_level = float(competency_state.get("level", 1.0))
        gap = max(0.0, round(required_level - current_level, 2))
        
        return {
            "required_level": required_level,
            "gap": gap
        }

    def _extract_all_source_chunks(self, questions: list[dict]) -> list[str]:
        """Extract all unique source chunks from quiz questions."""
        chunks = set()
        for q in questions:
            chunks.update(q.get("source_chunks", []))
        return list(chunks)

    def list_relevant_quizzes_for_official(self, user_id: str) -> list[dict]:
        """
        List role- and competency-personalized quizzes available for the current official.
        
        Deterministic policy:
        1. Explicitly assigned to user (Highest Priority)
        2. Critical competency gap (Priority 2)
        3. High-priority competency gap (Priority 3)
        4. Other identified competency gap (Priority 4)
        5. Role / Designation targeted (Priority 5)
        6. Role required competency (practice / refresher even if met) (Priority 6)
        
        Quizzes outside of these criteria are strictly excluded.
        """
        u_oid = ObjectId(user_id) if ObjectId.is_valid(user_id) else None
        user = None
        if u_oid:
            user = self.db.users.find_one({"_id": u_oid})
        if not user:
            user = self.db.users.find_one({"_id": str(user_id)})
            
        if not user:
            return []

        user_access_role = user.get("access_role")
        if user_access_role in ("TRAINER", "ADMIN"):
            cursor = self.db.quizzes.find({"status": {"$in": ["PUBLISHED", "ASSIGNED"]}})
            if hasattr(cursor, "sort"):
                cursor = cursor.sort("created_at", -1)
            raw_list = list(cursor)
            results = []
            for q in raw_list:
                q_copy = dict(q)
                q_copy["relevance_reason"] = "ROLE_TARGETED"
                q_copy["relevance_explanation"] = "Administrative catalogue access."
                q_copy["priority"] = 1
                safe_questions = []
                for qu in q.get("questions", []):
                    safe_questions.append({
                        "question_id": str(qu.get("question_id", qu.get("_id", ""))),
                        "question": qu.get("question", ""),
                        "options": qu.get("options", []),
                        "difficulty": qu.get("difficulty", "MEDIUM"),
                        "source_chunks": qu.get("source_chunks", []),
                    })
                q_copy["questions"] = safe_questions
                results.append(q_copy)
            return results

        user_dept = user.get("department")
        user_desig = user.get("government_designation") or user.get("designation")
        user_desig_id = user.get("designation_id")
        user_role_id = user.get("role_id")

        from app.roles.resolver import resolve_role_for_user
        resolved_role_id = user_role_id
        if not resolved_role_id and (user_dept or user_desig):
            resolved_role_id = resolve_role_for_user(self.db, user_dept, user_desig)

        role_doc = None
        if resolved_role_id:
            u_r_oid = ObjectId(resolved_role_id) if ObjectId.is_valid(resolved_role_id) else resolved_role_id
            if hasattr(self.db, "roles"):
                role_doc = self.db.roles.find_one({"$or": [{"_id": u_r_oid}, {"role_code": resolved_role_id}, {"role_id": resolved_role_id}]})

        role_code = (role_doc.get("role_code") or role_doc.get("role_id")) if role_doc else (user.get("role") or user_role_id)
        role_name = role_doc.get("role_name") if role_doc else user_desig

        req_comp_codes = set()
        role_query_ids = []
        if resolved_role_id:
            role_query_ids.append(resolved_role_id)
            if ObjectId.is_valid(resolved_role_id):
                role_query_ids.append(ObjectId(resolved_role_id))
        if user_role_id:
            role_query_ids.append(user_role_id)
            if ObjectId.is_valid(user_role_id):
                role_query_ids.append(ObjectId(user_role_id))
        if user.get("role"):
            role_query_ids.append(user["role"])
        if role_doc:
            role_query_ids.append(role_doc.get("_id"))
            if role_doc.get("role_code"):
                role_query_ids.append(role_doc["role_code"])
            if role_doc.get("role_id"):
                role_query_ids.append(role_doc["role_id"])

        reqs = []
        if role_query_ids and hasattr(self.db, "role_requirements"):
            reqs = list(self.db.role_requirements.find({"role_id": {"$in": role_query_ids}}))
            for r in reqs:
                if r.get("competency_code"):
                    req_comp_codes.add(r["competency_code"])
                elif r.get("competency_id"):
                    cid = r["competency_id"]
                    if isinstance(cid, str) and not ObjectId.is_valid(cid):
                        req_comp_codes.add(cid)
                    else:
                        c_doc = self.db.competencies.find_one({"$or": [{"_id": cid}, {"code": cid}, {"competency_id": cid}]})
                        if c_doc:
                            req_comp_codes.add(c_doc.get("code") or c_doc.get("competency_id") or str(cid))

        gap_map = {}
        critical_gap_codes = set()
        high_gap_codes = set()
        other_gap_codes = set()

        try:
            from app.skill_gaps.service import calculate_skill_gaps
            gap_res = calculate_skill_gaps(self.db, user_id)
            for g in gap_res.gaps:
                code = g.competency_code
                gap_size = float(g.gap_size)
                is_gap = bool(g.is_gap)
                cur_lvl = float(g.current_level) if g.current_level is not None else None
                req_lvl = float(g.required_level) if g.required_level is not None else None
                
                gap_map[code] = {
                    "is_gap": is_gap,
                    "gap_size": gap_size,
                    "current_level": cur_lvl,
                    "required_level": req_lvl,
                    "priority_label": g.priority,
                }

                if is_gap:
                    if g.priority == "CRITICAL" or gap_size >= 1.0:
                        critical_gap_codes.add(code)
                    elif g.priority == "HIGH" or gap_size >= 0.5:
                        high_gap_codes.add(code)
                    else:
                        other_gap_codes.add(code)
        except Exception:
            pass

        # Fallback gap calculation if engine raised or returned empty
        if not gap_map and reqs:
            user_oid = ObjectId(user_id) if ObjectId.is_valid(user_id) else user_id
            for req in reqs:
                code = req.get("competency_code")
                cid = req.get("competency_id")
                if not code and isinstance(cid, str) and not ObjectId.is_valid(cid):
                    code = cid
                elif not code and cid:
                    c_doc = self.db.competencies.find_one({"$or": [{"_id": cid}, {"code": cid}, {"competency_id": cid}]})
                    if c_doc:
                        code = c_doc.get("code") or c_doc.get("competency_id")
                if not code:
                    continue

                req_lvl = float(req.get("required_level", 3.0))

                # Look up user competency profile
                p_conditions = [
                    {"user_id": user_oid},
                    {"user_id": str(user_id)},
                ]
                comp_conditions = []
                if cid:
                    comp_conditions.extend([{"competency_id": cid}, {"competency_id": str(cid)}])
                if code:
                    comp_conditions.extend([{"competency_id": code}, {"competency_code": code}])

                prof = None
                if comp_conditions:
                    prof = self.db.competency_profiles.find_one({
                        "$and": [
                            {"$or": p_conditions},
                            {"$or": comp_conditions},
                        ]
                    })

                cur_lvl = 1.0
                if prof:
                    cur_lvl = float(prof.get("current_level") if prof.get("current_level") is not None else (prof.get("level") or 1.0))

                gap_size = max(0.0, round(req_lvl - cur_lvl, 2))
                is_gap = gap_size > 0.0
                priority_label = "CRITICAL" if gap_size >= 1.0 else ("HIGH" if gap_size >= 0.5 else "MEDIUM")
                gap_map[code] = {
                    "is_gap": is_gap,
                    "gap_size": gap_size,
                    "current_level": cur_lvl,
                    "required_level": req_lvl,
                    "priority_label": priority_label,
                }
                if is_gap:
                    if gap_size >= 1.0:
                        critical_gap_codes.add(code)
                    elif gap_size >= 0.5:
                        high_gap_codes.add(code)
                    else:
                        other_gap_codes.add(code)

        cursor = self.db.quizzes.find({"status": {"$in": ["PUBLISHED", "ASSIGNED"]}})
        candidate_quizzes = list(cursor)

        relevant_quizzes = []
        user_id_str = str(user_id)

        for quiz in candidate_quizzes:
            assigned_to = [str(x) for x in quiz.get("assigned_to", [])] + [str(x) for x in quiz.get("assigned_user_ids", [])]
            comp_code = quiz.get("competency_code", "")
            target_comps = set(quiz.get("target_competency_ids", []))
            if comp_code:
                target_comps.add(comp_code)

            target_roles = set(quiz.get("target_role_ids", []))
            target_desigs = set(quiz.get("target_designation_ids", []))

            is_relevant = False
            relevance_reason = None
            relevance_explanation = None
            sort_priority = 99
            gap_size = 0.0
            is_gap = False
            cur_lvl = None
            req_lvl = None

            comp_gap_info = gap_map.get(comp_code)
            if not comp_gap_info:
                for tc in target_comps:
                    if tc in gap_map:
                        comp_gap_info = gap_map[tc]
                        break

            if comp_gap_info:
                gap_size = comp_gap_info["gap_size"]
                is_gap = comp_gap_info["is_gap"]
                cur_lvl = comp_gap_info["current_level"]
                req_lvl = comp_gap_info["required_level"]

            # Criterion 1: Explicit Trainer Assignment
            if user_id_str in assigned_to:
                is_relevant = True
                relevance_reason = "ASSIGNED_BY_TRAINER"
                relevance_explanation = "Directly assigned by your trainer."
                sort_priority = 1

            # Criterion 2: Critical Competency Gap
            elif target_comps.intersection(critical_gap_codes):
                is_relevant = True
                relevance_reason = "CRITICAL_GAP"
                relevance_explanation = "Recommended because this is an active critical competency gap."
                sort_priority = 2

            # Criterion 3: High Competency Gap
            elif target_comps.intersection(high_gap_codes):
                is_relevant = True
                relevance_reason = "HIGH_GAP"
                relevance_explanation = "Targeted for your identified high-priority skill gap."
                sort_priority = 3

            # Criterion 4: Other Identified Gap
            elif target_comps.intersection(other_gap_codes):
                is_relevant = True
                relevance_reason = "IDENTIFIED_GAP"
                relevance_explanation = "Targeted remediation for your competency gap."
                sort_priority = 4

            # Criterion 5: Target Designation or Role Match (for non-required competencies)
            elif (
                (
                    (user_desig_id and user_desig_id in target_desigs)
                    or (user_desig and any(user_desig.lower() == td.lower() for td in target_desigs))
                    or (role_code and role_code in target_roles)
                    or (resolved_role_id and str(resolved_role_id) in target_roles)
                    or (user.get("role") and user.get("role") in target_roles)
                    or (user_role_id and str(user_role_id) in target_roles)
                )
                and not target_comps.intersection(req_comp_codes)
            ):
                is_relevant = True
                relevance_reason = "ROLE_TARGETED"
                relevance_explanation = f"Tailored for your official role ({user_desig or role_name})."
                sort_priority = 5

            # Criterion 6: Required Competency (Practice / Refresher even if met)
            elif target_comps.intersection(req_comp_codes):
                is_relevant = True
                relevance_reason = "REQUIRED_COMPETENCY"
                relevance_explanation = "Part of your official role competency requirements."
                sort_priority = 6

            if is_relevant:
                quiz_copy = dict(quiz)
                quiz_copy["relevance_reason"] = relevance_reason
                quiz_copy["relevance_explanation"] = relevance_explanation
                quiz_copy["priority"] = sort_priority
                quiz_copy["is_gap"] = is_gap
                quiz_copy["gap_size"] = gap_size
                quiz_copy["current_level"] = cur_lvl
                quiz_copy["required_level"] = req_lvl
                
                # Sanitize questions (hide correct answers and explanations)
                safe_questions = []
                for q in quiz.get("questions", []):
                    safe_questions.append({
                        "question_id": str(q.get("question_id", q.get("_id", ""))),
                        "question": q.get("question", ""),
                        "options": q.get("options", []),
                        "difficulty": q.get("difficulty", "MEDIUM"),
                        "source_chunks": q.get("source_chunks", []),
                    })
                quiz_copy["questions"] = safe_questions
                relevant_quizzes.append(quiz_copy)

        def _sort_key(item):
            created_at = item.get("created_at")
            created_ts = created_at.timestamp() if isinstance(created_at, datetime) else 0.0
            return (
                item.get("priority", 99),
                -float(item.get("gap_size", 0.0) or 0.0),
                -created_ts,
            )

        relevant_quizzes.sort(key=_sort_key)
        return relevant_quizzes

    def get_explicitly_assigned_quizzes(self, user_id: str) -> list[dict]:
        """
        SOURCE A — EXPLICIT ASSIGNMENT
        Retrieve quizzes explicitly assigned to this official by a trainer/admin.
        Does NOT depend on recommendation scoring.
        """
        user_id_str = str(user_id)
        query = {
            "$or": [
                {"assigned_to": user_id_str},
                {"assigned_user_ids": user_id_str},
            ]
        }
        cursor = self.db.quizzes.find(query)
        if hasattr(cursor, "sort"):
            cursor = cursor.sort("created_at", -1)
        raw_list = list(cursor)

        # Batch lookup trainer names
        trainer_ids = [q.get("trainer_id") for q in raw_list if q.get("trainer_id")]
        trainer_map = {}
        if trainer_ids and hasattr(self.db, "users"):
            t_query = {"$or": [{"_id": {"$in": trainer_ids}}, {"_id": {"$in": [ObjectId(x) for x in trainer_ids if ObjectId.is_valid(x)]}}]}
            for u in self.db.users.find(t_query):
                trainer_map[str(u["_id"])] = u.get("full_name") or u.get("name") or "Curriculum Trainer"

        assigned_quizzes = []
        for q in raw_list:
            q_copy = dict(q)
            trainer_id_str = str(q.get("trainer_id", ""))
            trainer_name = trainer_map.get(trainer_id_str) or q.get("trainer_name") or "Curriculum Trainer"
            q_copy["trainer_name"] = trainer_name
            q_copy["relevance_reason"] = "ASSIGNED_BY_TRAINER"
            q_copy["relevance_explanation"] = f"Directly assigned by {trainer_name}."
            q_copy["priority"] = 1
            q_copy["is_also_recommended"] = False

            # Sanitize questions (hide correct answers and explanations)
            safe_questions = []
            for qu in q.get("questions", []):
                safe_questions.append({
                    "question_id": str(qu.get("question_id", qu.get("_id", ""))),
                    "question": qu.get("question", ""),
                    "options": qu.get("options", []),
                    "difficulty": qu.get("difficulty", q.get("difficulty", "MEDIUM")),
                    "source_chunks": qu.get("source_chunks", []),
                })
            q_copy["questions"] = safe_questions
            assigned_quizzes.append(q_copy)

        return assigned_quizzes

    def recommend_quizzes_for_official(self, user_id: str, limit: int = 5) -> list[dict]:
        """
        SOURCE B — SYSTEM RECOMMENDATION
        Deterministic recommendation engine for government workforce competency development.
        
        Evaluates:
        official -> role/designation -> required competencies -> current competency -> competency gap -> relevant quiz
        
        Hard Relevance Filter (Phase 5):
        Must target role requirement, active gap, or specific role profile.
        
        Scoring Formula (Phase 4):
        40% competency-gap relevance + 25% designation/role relevance + 15% gap severity
        + 10% difficulty suitability + 10% prerequisite compatibility
        """
        u_oid = ObjectId(user_id) if ObjectId.is_valid(user_id) else None
        user = None
        if u_oid:
            user = self.db.users.find_one({"_id": u_oid})
        if not user:
            user = self.db.users.find_one({"_id": str(user_id)})
        if not user:
            return []

        user_dept = user.get("department")
        user_desig = user.get("government_designation") or user.get("designation")
        user_desig_id = user.get("designation_id")
        user_role_id = user.get("role_id")

        from app.roles.resolver import resolve_role_for_user
        resolved_role_id = user_role_id
        if not resolved_role_id and (user_dept or user_desig):
            resolved_role_id = resolve_role_for_user(self.db, user_dept, user_desig)

        role_doc = None
        if resolved_role_id:
            u_r_oid = ObjectId(resolved_role_id) if ObjectId.is_valid(resolved_role_id) else resolved_role_id
            if hasattr(self.db, "roles"):
                role_doc = self.db.roles.find_one({"$or": [{"_id": u_r_oid}, {"role_code": resolved_role_id}, {"role_id": resolved_role_id}]})

        role_code = (role_doc.get("role_code") or role_doc.get("role_id")) if role_doc else (user.get("role") or user_role_id)
        role_name = role_doc.get("role_name") if role_doc else (user_desig or "Government Official")

        req_comp_codes = set()
        role_query_ids = []
        if resolved_role_id:
            role_query_ids.append(resolved_role_id)
            if ObjectId.is_valid(resolved_role_id):
                role_query_ids.append(ObjectId(resolved_role_id))
        if user_role_id:
            role_query_ids.append(user_role_id)
            if ObjectId.is_valid(user_role_id):
                role_query_ids.append(ObjectId(user_role_id))
        if user.get("role"):
            role_query_ids.append(user["role"])
        if role_doc:
            role_query_ids.append(role_doc.get("_id"))
            if role_doc.get("role_code"):
                role_query_ids.append(role_doc["role_code"])
            if role_doc.get("role_id"):
                role_query_ids.append(role_doc["role_id"])

        reqs = []
        if role_query_ids and hasattr(self.db, "role_requirements"):
            reqs = list(self.db.role_requirements.find({"role_id": {"$in": role_query_ids}}))
            for r in reqs:
                if r.get("competency_code"):
                    req_comp_codes.add(r["competency_code"])
                elif r.get("competency_id"):
                    cid = r["competency_id"]
                    if isinstance(cid, str) and not ObjectId.is_valid(cid):
                        req_comp_codes.add(cid)
                    else:
                        c_doc = self.db.competencies.find_one({"$or": [{"_id": cid}, {"code": cid}, {"competency_id": cid}]})
                        if c_doc:
                            req_comp_codes.add(c_doc.get("code") or c_doc.get("competency_id") or str(cid))

        gap_map = {}
        try:
            from app.skill_gaps.service import calculate_skill_gaps
            gap_res = calculate_skill_gaps(self.db, user_id)
            for g in gap_res.gaps:
                code = g.competency_code
                gap_size = float(g.gap_size)
                is_gap = bool(g.is_gap)
                cur_lvl = float(g.current_level) if g.current_level is not None else None
                req_lvl = float(g.required_level) if g.required_level is not None else None
                
                gap_map[code] = {
                    "is_gap": is_gap,
                    "gap_size": gap_size,
                    "current_level": cur_lvl,
                    "required_level": req_lvl,
                    "priority_label": g.priority,
                    "competency_name": g.competency_name,
                }
        except Exception:
            pass

        # Fallback gap calculation if engine raised or returned empty
        if not gap_map and reqs:
            user_oid = ObjectId(user_id) if ObjectId.is_valid(user_id) else user_id
            for req in reqs:
                code = req.get("competency_code")
                cid = req.get("competency_id")
                comp_name = None
                if not code and isinstance(cid, str) and not ObjectId.is_valid(cid):
                    code = cid
                elif cid:
                    c_doc = self.db.competencies.find_one({"$or": [{"_id": cid}, {"code": cid}, {"competency_id": cid}]})
                    if c_doc:
                        code = c_doc.get("code") or c_doc.get("competency_id")
                        comp_name = c_doc.get("name") or c_doc.get("competency_name")
                if not code:
                    continue

                req_lvl = float(req.get("required_level", 3.0))

                p_conditions = [
                    {"user_id": user_oid},
                    {"user_id": str(user_id)},
                ]
                comp_conditions = []
                if cid:
                    comp_conditions.extend([{"competency_id": cid}, {"competency_id": str(cid)}])
                if code:
                    comp_conditions.extend([{"competency_id": code}, {"competency_code": code}])

                prof = None
                if comp_conditions:
                    prof = self.db.competency_profiles.find_one({
                        "$and": [
                            {"$or": p_conditions},
                            {"$or": comp_conditions},
                        ]
                    })

                cur_lvl = 1.0
                if prof:
                    cur_lvl = float(prof.get("current_level") if prof.get("current_level") is not None else (prof.get("level") or 1.0))

                gap_size = max(0.0, round(req_lvl - cur_lvl, 2))
                is_gap = gap_size > 0.0
                gap_map[code] = {
                    "is_gap": is_gap,
                    "gap_size": gap_size,
                    "current_level": cur_lvl,
                    "required_level": req_lvl,
                    "priority_label": "CRITICAL" if gap_size >= 1.0 else ("HIGH" if gap_size >= 0.5 else "MEDIUM"),
                    "competency_name": comp_name or code.replace("_", " ").title(),
                }

        # Candidate pool: published quizzes
        cursor = self.db.quizzes.find({"status": {"$in": ["PUBLISHED", "ASSIGNED"]}})
        candidate_quizzes = list(cursor)

        recommended_items = []
        for quiz in candidate_quizzes:
            comp_code = quiz.get("competency_code", "")
            target_comps = set(quiz.get("target_competency_ids", []))
            if comp_code:
                target_comps.add(comp_code)

            target_roles = set(quiz.get("target_role_ids", []))
            target_desigs = set(quiz.get("target_designation_ids", []))

            # ----------------------------------------------------
            # PHASE 5: HARD RELEVANCE FILTER
            # Quiz must satisfy at least one strong condition:
            # 1. Targets a competency required for official's role
            # 2. Targets a competency where official has identified gap
            # 3. Targets official's role or designation directly
            # ----------------------------------------------------
            is_role_required = bool(target_comps.intersection(req_comp_codes))
            
            gap_competencies = {code for code, info in gap_map.items() if info.get("is_gap")}
            has_active_gap = bool(target_comps.intersection(gap_competencies))
            
            matches_role_or_desig = (
                (user_desig_id and user_desig_id in target_desigs)
                or (user_desig and any(user_desig.lower() == td.lower() for td in target_desigs))
                or (role_code and role_code in target_roles)
                or (resolved_role_id and str(resolved_role_id) in target_roles)
                or (user.get("role") and user.get("role") in target_roles)
                or (user_role_id and str(user_role_id) in target_roles)
            )

            # HARD FILTER: If none of the 3 conditions are met, DISQUALIFY immediately.
            if not (is_role_required or has_active_gap or matches_role_or_desig):
                continue

            # Find matching gap info if available
            comp_gap_info = gap_map.get(comp_code)
            if not comp_gap_info:
                for tc in target_comps:
                    if tc in gap_map:
                        comp_gap_info = gap_map[tc]
                        break

            gap_size = comp_gap_info["gap_size"] if comp_gap_info else 0.0
            is_gap = comp_gap_info["is_gap"] if comp_gap_info else False
            cur_lvl = comp_gap_info["current_level"] if comp_gap_info else None
            req_lvl = comp_gap_info["required_level"] if comp_gap_info else None
            comp_name = (comp_gap_info.get("competency_name") if comp_gap_info else None) or (comp_code.replace("_", " ").title() if comp_code else "Target Domain")

            # ----------------------------------------------------
            # PHASE 4: DETERMINISTIC PROTOTYPE SCORING
            # 40% Competency-Gap Relevance
            # 25% Designation/Role Relevance
            # 15% Gap Severity
            # 10% Difficulty Suitability
            # 10% Prerequisite Compatibility
            # ----------------------------------------------------
            # 1. Competency-Gap Relevance (40%)
            if is_gap:
                s_gap = 1.0
            elif is_role_required:
                s_gap = 0.6
            else:
                s_gap = 0.3

            # 2. Designation / Role Relevance (25%)
            if matches_role_or_desig:
                s_role = 1.0
            elif is_role_required:
                s_role = 0.8
            else:
                s_role = 0.4

            # 3. Gap Severity (15%)
            s_sev = min(1.0, gap_size / 3.0) if gap_size > 0 else 0.0

            # 4. Difficulty Suitability (10%)
            q_diff = (quiz.get("difficulty") or "MEDIUM").upper()
            ref_level = cur_lvl if cur_lvl is not None else 2.5
            if ref_level < 2.5:
                s_diff = 1.0 if q_diff == "EASY" else (0.7 if q_diff == "MEDIUM" else 0.4)
            elif ref_level <= 3.8:
                s_diff = 1.0 if q_diff == "MEDIUM" else (0.8 if q_diff == "EASY" else 0.7)
            else:
                s_diff = 1.0 if q_diff == "HARD" else (0.8 if q_diff == "MEDIUM" else 0.5)

            # 5. Prerequisite Compatibility (10%)
            s_pre = 1.0 if (cur_lvl is None or cur_lvl >= 1.0) else 0.6

            score = round(0.40 * s_gap + 0.25 * s_role + 0.15 * s_sev + 0.10 * s_diff + 0.10 * s_pre, 3)

            # ----------------------------------------------------
            # PHASE 10: EXPLAINABILITY (Human-readable reason)
            # ----------------------------------------------------
            if is_gap and cur_lvl is not None and req_lvl is not None:
                reason = f"Recommended because {comp_name} is a current competency gap for your role (Current: {cur_lvl:.2f} / Required: {req_lvl:.2f}, Gap: -{gap_size:.2f})."
            elif is_gap:
                reason = f"Recommended because {comp_name} is an active competency gap for your role."
            elif is_role_required:
                reason = f"Recommended for continuous practice in {comp_name}, a required competency for your role."
            else:
                reason = f"Recommended because this module is tailored for your official role ({role_name})."

            # Prepare safe quiz document
            safe_questions = []
            for qu in quiz.get("questions", []):
                safe_questions.append({
                    "question_id": str(qu.get("question_id", qu.get("_id", ""))),
                    "question": qu.get("question", ""),
                    "options": qu.get("options", []),
                    "difficulty": qu.get("difficulty", quiz.get("difficulty", "MEDIUM")),
                    "source_chunks": qu.get("source_chunks", []),
                })

            safe_quiz = dict(quiz)
            safe_quiz["questions"] = safe_questions
            safe_quiz["relevance_reason"] = "CRITICAL_GAP" if (is_gap and gap_size >= 1.0) else ("HIGH_GAP" if is_gap else ("REQUIRED_COMPETENCY" if is_role_required else "ROLE_TARGETED"))
            safe_quiz["relevance_explanation"] = reason
            safe_quiz["priority"] = 2 if (is_gap and gap_size >= 1.0) else (3 if is_gap else (6 if is_role_required else 5))
            safe_quiz["is_gap"] = is_gap
            safe_quiz["gap_size"] = gap_size
            safe_quiz["current_level"] = cur_lvl
            safe_quiz["required_level"] = req_lvl

            recommended_items.append({
                "quiz": safe_quiz,
                "primary_competency": comp_code or (list(target_comps)[0] if target_comps else "GENERAL"),
                "current_level": cur_lvl,
                "required_level": req_lvl,
                "gap": gap_size,
                "recommendation_score": score,
                "reason": reason,
                "role_name": role_name,
            })

        # Rank by score DESC -> gap DESC -> created_at DESC
        def _rec_sort_key(item):
            created_at = item["quiz"].get("created_at")
            created_ts = created_at.timestamp() if isinstance(created_at, datetime) else 0.0
            return (
                -item["recommendation_score"],
                -float(item.get("gap") or 0.0),
                -created_ts,
            )

        recommended_items.sort(key=_rec_sort_key)
        return recommended_items[:limit]

    def get_official_quiz_feed(self, user_id: str, limit: int = 5) -> dict:
        """
        PHASE 2 & 8 & 9: Complete Official Quiz Feed.
        Separates Source A (Trainer-Assigned) from Source B (System-Recommended).
        Applies Deduplication: if assigned and recommended, stays in Assigned with a badge.
        """
        assigned_quizzes = self.get_explicitly_assigned_quizzes(user_id)
        # Fetch candidate recommendations (buffer slightly to handle deduplication)
        buffer_limit = limit + len(assigned_quizzes)
        all_recommended = self.recommend_quizzes_for_official(user_id, limit=buffer_limit)

        assigned_ids = {str(q["_id"]) for q in assigned_quizzes}
        recommended_ids_in_assigned = {
            str(r["quiz"]["_id"]) for r in all_recommended if str(r["quiz"]["_id"]) in assigned_ids
        }

        # Deduplication flag for assigned quizzes
        for q in assigned_quizzes:
            if str(q["_id"]) in recommended_ids_in_assigned:
                q["is_also_recommended"] = True
                # Keep prompt Phase 8 badge intent
                q["relevance_explanation"] = "Directly assigned by trainer. Also relevant to your active competency gap."

        # Filter out from recommended if already assigned
        final_recommended = [
            r for r in all_recommended if str(r["quiz"]["_id"]) not in assigned_ids
        ][:limit]

        return {
            "assigned": assigned_quizzes,
            "recommended": final_recommended,
            "meta": {
                "total_assigned": len(assigned_quizzes),
                "total_recommended": len(final_recommended),
                "recommendation_reasoning": True,
            },
        }


def is_quiz_relevant_to_user(database: Database, user: dict, quiz: dict) -> bool:
    """
    Check if a published/assigned quiz is relevant to a specific user.
    Used for authorization boundaries so officials cannot take unauthorized quizzes.
    """
    if not user:
        return False
        
    user_access_role = user.get("access_role")
    if user_access_role in ("TRAINER", "ADMIN"):
        return True

    user_id_str = str(user.get("_id", ""))
    assigned_to = [str(x) for x in quiz.get("assigned_to", [])] + [str(x) for x in quiz.get("assigned_user_ids", [])]
    if user_id_str in assigned_to:
        return True

    user_dept = user.get("department")
    user_desig = user.get("government_designation") or user.get("designation")
    user_desig_id = user.get("designation_id")
    user_role_id = user.get("role_id")

    from app.roles.resolver import resolve_role_for_user
    resolved_role_id = user_role_id
    if not resolved_role_id and (user_dept or user_desig):
        resolved_role_id = resolve_role_for_user(database, user_dept, user_desig)

    role_doc = None
    if resolved_role_id:
        u_r_oid = ObjectId(resolved_role_id) if ObjectId.is_valid(resolved_role_id) else resolved_role_id
        if hasattr(database, "roles"):
            role_doc = database.roles.find_one({"$or": [{"_id": u_r_oid}, {"role_code": resolved_role_id}, {"role_id": resolved_role_id}]})

    role_code = (role_doc.get("role_code") or role_doc.get("role_id")) if role_doc else (user.get("role") or user_role_id)

    # Check target designations and roles
    target_desigs = set(quiz.get("target_designation_ids", []))
    target_roles = set(quiz.get("target_role_ids", []))

    if (
        (user_desig_id and user_desig_id in target_desigs)
        or (user_desig and any(user_desig.lower() == td.lower() for td in target_desigs))
        or (role_code and role_code in target_roles)
        or (resolved_role_id and str(resolved_role_id) in target_roles)
        or (user.get("role") and user.get("role") in target_roles)
        or (user_role_id and str(user_role_id) in target_roles)
    ):
        return True

    # Check competencies against role requirements
    comp_code = quiz.get("competency_code", "")
    target_comps = set(quiz.get("target_competency_ids", []))
    if comp_code:
        target_comps.add(comp_code)

    role_query_ids = []
    if resolved_role_id:
        role_query_ids.append(resolved_role_id)
        if ObjectId.is_valid(resolved_role_id):
            role_query_ids.append(ObjectId(resolved_role_id))
    if user_role_id:
        role_query_ids.append(user_role_id)
        if ObjectId.is_valid(user_role_id):
            role_query_ids.append(ObjectId(user_role_id))
    if user.get("role"):
        role_query_ids.append(user["role"])
    if role_doc:
        role_query_ids.append(role_doc.get("_id"))
        if role_doc.get("role_code"):
            role_query_ids.append(role_doc["role_code"])
        if role_doc.get("role_id"):
            role_query_ids.append(role_doc["role_id"])

    if role_query_ids and hasattr(database, "role_requirements"):
        reqs = list(database.role_requirements.find({"role_id": {"$in": role_query_ids}}))
        req_comp_codes = set()
        for r in reqs:
            if r.get("competency_code"):
                req_comp_codes.add(r["competency_code"])
            elif r.get("competency_id"):
                cid = r["competency_id"]
                if isinstance(cid, str) and not ObjectId.is_valid(cid):
                    req_comp_codes.add(cid)
                else:
                    c_doc = database.competencies.find_one({"$or": [{"_id": cid}, {"code": cid}, {"competency_id": cid}]})
                    if c_doc:
                        req_comp_codes.add(c_doc.get("code") or c_doc.get("competency_id") or str(cid))
        if target_comps.intersection(req_comp_codes):
            return True

    return False
