"""Quiz service - business logic for quiz creation, submission, scoring, and competency updates."""
from datetime import datetime
from typing import Optional

from bson import ObjectId
from pymongo.database import Database

from app.competencies.models import EvidenceType
from app.assessments.repository import (
    insert_evidence,
    upsert_profile,
)
from app.quizzes import repository as quiz_repo
from app.quizzes.models import Quiz, QuizAttempt, QuizStatus, QuizQuestion


class QuizServiceError(Exception):
    """Quiz service error."""
    pass


class QuizService:
    """Quiz service with business logic."""

    def __init__(self, database: Database):
        self.db = database

    def create_quiz(
        self,
        user_id: str,
        material_id: str,
        competency_code: str,
        questions: list[dict],
    ) -> dict:
        """
        Create a quiz from pre-generated MCQs.
        
        Note: MCQs are generated by Phase 6 (/api/v1/materials/{material_id}/generate-questions).
        This endpoint receives the generated questions and stores them in a quiz.
        
        Flow:
        1. Validate user owns the material
        2. Validate material is READY
        3. Validate competency exists
        4. Store questions in quiz
        5. Return quiz
        """
        if not ObjectId.is_valid(user_id):
            raise QuizServiceError("Invalid user ID")
        if not ObjectId.is_valid(material_id):
            raise QuizServiceError("Invalid material ID")

        user_oid = ObjectId(user_id)
        material_oid = ObjectId(material_id)

        # Validate material exists and belongs to user
        material = self.db.learning_materials.find_one(
            {"_id": material_oid, "user_id": {"$in": [str(user_id), user_oid]}}
        )
        if not material:
            raise QuizServiceError("Material not found or does not belong to user")

        # Validate material is READY
        if material.get("status") != "READY":
            raise QuizServiceError(
                f"Material is not ready (status: {material.get('status')})"
            )

        # Validate competency exists
        competency = self.db.competencies.find_one({"code": competency_code})
        if not competency:
            raise QuizServiceError(f"Competency not found: {competency_code}")

        if not questions:
            raise QuizServiceError("No questions provided")

        # Convert generated MCQs to quiz questions (preserve all data)
        quiz_questions = []
        for idx, mcq in enumerate(questions):
            question = QuizQuestion(
                question_id=f"q_{idx + 1}",
                question=mcq["question"],
                options=mcq["options"],
                correct_answer=mcq["correct_answer"],
                explanation=mcq["explanation"],
                difficulty=mcq["difficulty"],
                source_chunks=mcq.get("source_chunks", []),
            )
            quiz_questions.append(dict(question))

        # Create quiz document
        quiz_doc = Quiz.create(
            user_id=user_oid,
            material_id=material_oid,
            competency_code=competency_code,
            title=f"{competency_code} Quiz - {material.get('original_filename')}",
            questions=quiz_questions,
            question_count=len(quiz_questions),
        )

        # Insert into database
        quiz_id = quiz_repo.insert_quiz(self.db, quiz_doc)
        quiz_doc["_id"] = quiz_id

        return quiz_doc

    def get_quiz(self, user_id: str, quiz_id: str) -> dict:
        """
        Retrieve a quiz (without correct answers).
        
        Correct answers must not be exposed before submission.
        """
        quiz = quiz_repo.get_quiz_by_id(self.db, quiz_id, user_id)
        if not quiz:
            raise QuizServiceError("Quiz not found")

        # Remove correct answers from questions before returning
        questions_for_response = []
        for q in quiz.get("questions", []):
            safe_question = {
                "question_id": q["question_id"],
                "question": q["question"],
                "options": q["options"],
                "difficulty": q["difficulty"],
                "source_chunks": q.get("source_chunks", []),
            }
            questions_for_response.append(safe_question)

        quiz["questions"] = questions_for_response
        return quiz

    def submit_quiz(
        self,
        user_id: str,
        quiz_id: str,
        answers: list[dict],
    ) -> dict:
        """
        Submit quiz answers and calculate score.
        
        Flow:
        1. Validate user owns quiz
        2. Validate quiz is not already submitted
        3. Validate all questions answered
        4. Calculate score server-side
        5. Create quiz attempt
        6. Create competency evidence
        7. Update competency profile (deterministic rule)
        8. Return result with before/after competency
        """
        # Get quiz
        quiz = quiz_repo.get_quiz_by_id(self.db, quiz_id, user_id)
        if not quiz:
            raise QuizServiceError("Quiz not found")

        # Check if already submitted
        if quiz.get("status") == QuizStatus.SUBMITTED:
            raise QuizServiceError("Quiz already submitted")

        # Validate answers
        question_ids = {q["question_id"] for q in quiz["questions"]}
        submitted_ids = {a["question_id"] for a in answers}

        if submitted_ids != question_ids:
            raise QuizServiceError(
                f"Missing or extra question IDs. Expected {question_ids}, got {submitted_ids}"
            )

        # Check for duplicates
        if len(submitted_ids) != len([a["question_id"] for a in answers]):
            raise QuizServiceError("Duplicate question IDs in submission")

        # Create answer map
        answer_map = {a["question_id"]: a["selected_answer"] for a in answers}

        # Calculate score server-side
        correct_count = 0
        attempt_answers = []

        for question in quiz["questions"]:
            q_id = question["question_id"]
            selected = answer_map[q_id]
            correct = question["correct_answer"]
            is_correct = selected.upper() == correct.upper()

            if is_correct:
                correct_count += 1

            attempt_answers.append({
                "question_id": q_id,
                "selected_answer": selected.upper(),
                "is_correct": is_correct,
            })

        total_questions = len(quiz["questions"])
        percentage = (correct_count / total_questions * 100) if total_questions > 0 else 0

        # Create quiz attempt
        user_oid = ObjectId(user_id)
        attempt_doc = QuizAttempt.create(
            quiz_id=ObjectId(quiz_id),
            user_id=user_oid,
            answers=attempt_answers,
            score=correct_count,
            percentage=percentage,
            correct_count=correct_count,
            total_questions=total_questions,
        )

        attempt_id = quiz_repo.insert_quiz_attempt(self.db, attempt_doc)

        # Update quiz with score
        now = datetime.utcnow()
        quiz_repo.update_quiz_with_score(
            self.db,
            quiz_id,
            user_id,
            correct_count,
            percentage,
            now,
        )

        # Get competency before update
        competency_code = quiz["competency_code"]
        competency_before = self._get_current_competency(user_oid, competency_code)

        # Get competency ObjectId
        competency_doc = self.db.competencies.find_one({"code": competency_code})
        competency_oid = ObjectId(competency_doc["_id"]) if competency_doc else ObjectId()

        # Create evidence
        evidence_doc = {
            "_id": ObjectId(),
            "user_id": user_oid,
            "competency_code": competency_code,
            "competency_id": competency_oid,
            "evidence_type": EvidenceType.QUIZ,
            "source": "AI_QUIZ",
            "quiz_id": ObjectId(quiz_id),
            "attempt_id": ObjectId(attempt_id),
            "quiz_percentage": percentage,
            "score": percentage,  # Normalized 0-100
            "weight": 1.0,  # Quiz evidence weight (can be configured)
            "created_at": now,
            "metadata": {
                "material_id": str(quiz["material_id"]),
                "question_count": total_questions,
                "correct_count": correct_count,
                "source_chunks": self._extract_all_source_chunks(quiz["questions"]),
            }
        }
        insert_evidence(self.db, evidence_doc)

        # Update competency profile (deterministic rule)
        competency_after = self._update_competency_deterministic(
            user_oid,
            competency_code,
            percentage,
        )

        # Get skill gap before and after
        skill_gap_before = self._calculate_skill_gap(user_oid, competency_code, competency_before)
        skill_gap_after = self._calculate_skill_gap(user_oid, competency_code, competency_after)

        # Build explanations
        explanations = []
        for question in quiz["questions"]:
            q_id = question["question_id"]
            answer = next((a for a in attempt_answers if a["question_id"] == q_id), None)

            explanations.append({
                "question_id": q_id,
                "question": question["question"],
                "options": question["options"],
                "your_answer": answer["selected_answer"],
                "correct_answer": question["correct_answer"],
                "explanation": question["explanation"],
                "difficulty": question["difficulty"],
                "source_chunks": question.get("source_chunks", []),
                "is_correct": answer["is_correct"],
            })

        return {
            "_id": attempt_id,
            "quiz_id": quiz_id,
            "score": correct_count,
            "percentage": percentage,
            "correct_count": correct_count,
            "total_questions": total_questions,
            "competency": {
                "competency_code": competency_code,
                "competency_level_before": competency_before["level"],
                "competency_level_after": competency_after["level"],
                "confidence_before": competency_before["confidence"],
                "confidence_after": competency_after["confidence"],
                "improvement": round(competency_after["level"] - competency_before["level"], 2),
            },
            "skill_gap": {
                "competency_code": competency_code,
                "current_level": competency_after["level"],
                "required_level": skill_gap_after["required_level"],
                "gap_before": skill_gap_before["gap"],
                "gap_after": skill_gap_after["gap"],
            },
            "explanations": explanations,
            "submitted_at": now,
        }

    def _get_current_competency(self, user_id: ObjectId, competency_code: str) -> dict:
        """Get current competency level and confidence for a user."""
        competency = self.db.competencies.find_one({"code": competency_code})
        if not competency:
            return {"level": 2.5, "confidence": 0.5}  # Default middle value

        competency_oid = ObjectId(competency["_id"]) if isinstance(competency["_id"], str) else competency["_id"]
        
        profile = self.db.competency_profiles.find_one({
            "user_id": user_id,
            "competency_id": competency_oid,
        })

        if not profile:
            return {"level": 2.5, "confidence": 0.5}

        return {
            "level": profile.get("level", 2.5),
            "confidence": profile.get("confidence", 0.5),
        }

    def _update_competency_deterministic(
        self,
        user_id: ObjectId,
        competency_code: str,
        quiz_percentage: float,
    ) -> dict:
        """
        Update competency profile using deterministic rule.
        
        Formula:
        - 0-39%: Weak (level 1.5, confidence 0.3)
        - 40-59%: Developing (level 2.5, confidence 0.5)
        - 60-79%: Competent (level 3.5, confidence 0.7)
        - 80-100%: Strong (level 4.5, confidence 0.9)
        
        This is a conservative approach:
        - Does not blindly overwrite existing profile
        - Creates evidence that supports future recalculation
        - Confidence is bounded based on quiz size
        """
        if quiz_percentage < 40:
            new_level = 1.5
            new_confidence = 0.3
        elif quiz_percentage < 60:
            new_level = 2.5
            new_confidence = 0.5
        elif quiz_percentage < 80:
            new_level = 3.5
            new_confidence = 0.7
        else:
            new_level = 4.5
            new_confidence = 0.9

        competency = self.db.competencies.find_one({"code": competency_code})
        if not competency:
            return {"level": new_level, "confidence": new_confidence}

        competency_oid = ObjectId(competency["_id"]) if isinstance(competency["_id"], str) else competency["_id"]

        # Upsert profile (creates if not exists, updates if exists)
        update_doc = {
            "level": new_level,
            "confidence": new_confidence,
            "last_updated_at": datetime.utcnow(),
            "last_evidence_type": EvidenceType.QUIZ,
        }

        upsert_profile(self.db, user_id, competency_oid, update_doc)

        return {"level": new_level, "confidence": new_confidence}

    def _calculate_skill_gap(
        self,
        user_id: ObjectId,
        competency_code: str,
        competency_state: dict,
    ) -> dict:
        """
        Calculate skill gap for a competency.
        
        Reuses Phase 5 logic:
        gap = max(0, required_level - current_level)
        """
        user = self.db.users.find_one({"_id": user_id})
        role_id = user.get("role_id") if user else None
        
        competency = self.db.competencies.find_one({"code": competency_code})
        competency_oid = competency["_id"] if competency else None
        
        req = None
        if role_id and competency_oid:
            role_oid = ObjectId(role_id) if isinstance(role_id, str) and ObjectId.is_valid(role_id) else role_id
            req = self.db.role_requirements.find_one({"role_id": role_oid, "competency_id": competency_oid})
            
        required_level = float(req.get("required_level", 3.0)) if req else 3.0
        current_level = float(competency_state.get("level", 1.0))
        gap = max(0.0, round(required_level - current_level, 2))
        
        return {
            "required_level": required_level,
            "gap": gap
        }

    def _extract_all_source_chunks(self, questions: list[dict]) -> list[str]:
        """Extract all unique source chunks from quiz questions."""
        chunks = set()
        for q in questions:
            chunks.update(q.get("source_chunks", []))
        return list(chunks)
